// app-preact/src/components/counter.tsx
import { decrement, increment } from "../../../pkg/wasm"
import { useRustCtx } from "../hooks/hooks"
import { AppConfig } from "../types"

export default function Counter() {
    const [config] = useRustCtx<AppConfig | null>('app_started', null)
    const [count] = useRustCtx('counter_updated', config?.count)

    return (
        <div className="flex flex-col space-y-4">
            <h2>Count: {count}</h2>
            <div className="flex gap-2">
                <button onClick={decrement}>Decrement</button>
                <button onClick={increment}>Increment</button>
            </div>
        </div>
    )
}

// app-svelte/src/lib/components/counter.svelte
<script lang="ts">
	import * as Card from '$lib/components/ui/card';
	import { useRustCtx } from '$lib/hooks/useRustCtx.svelte';
	import type { AppConfig } from '$lib/types';
	import { decrement, increment } from '../../../../pkg/wasm';
	import Button from './ui/button/button.svelte';

	let config = useRustCtx<AppConfig | null>('app_started', null);
	let count = useRustCtx<number | null>('counter_updated', null);
</script>

<Card.Root class="text-gray-300">
	<Card.Header>
		<Card.Title>Count</Card.Title>
	</Card.Header>
	<Card.Content>
		<p>The count is: {count.value ?? config.value?.count}</p>
	</Card.Content>
	<Card.Footer class="flex gap-2">
		<Button variant="outline" onclick={decrement}>Decrement</Button>
		<Button variant="outline" onclick={increment}>Increment</Button>
	</Card.Footer>
</Card.Root>
